"""
core/medallion/contracts_md.py — Render Medallion contracts JSON → MD.

The MD files are PR-reviewable surfaces regenerated from the JSON on every
change (never the source of truth, never hand-edited). Section style follows
the existing `interns/reports/derived_feature_reviews/md/` template:
  - Why This Was Proposed
  - Why Not Ground Truth
  - Remaining Risk
"""
from __future__ import annotations

from core.medallion.star_schema import StarSchema
from core.medallion.silver_contract import SilverContract, TableContract
from core.medallion.lineage import Lineage


# ── star schema ────────────────────────────────────────────────────────────────

def render_star_schema_md(schema: StarSchema) -> str:
    lines: list[str] = []
    lines.append(f"# Star Schema — {schema.workspace}")
    lines.append("")
    lines.append("Generated by the Medallion Architect. Source of truth is `star_schema.json`.")
    lines.append("This document is regenerated; do not hand-edit.")
    lines.append("")

    if schema.derivation_reasoning:
        lines.append("## Why This Was Proposed")
        lines.append("")
        lines.append(schema.derivation_reasoning)
        lines.append("")

    lines.append("## Facts")
    lines.append("")
    if not schema.facts:
        lines.append("_No fact tables defined yet._")
        lines.append("")
    for f in schema.facts:
        lines.append(f"### `fact_{f.name}`" if not f.name.startswith("fact_") else f"### `{f.name}`")
        lines.append("")
        lines.append(f"- **Grain**: {f.grain or '_not declared_'}")
        if f.source_silver_tables:
            lines.append(f"- **Source Silver tables**: {', '.join(f'`{s}`' for s in f.source_silver_tables)}")
        if f.measures:
            lines.append(f"- **Measures**: {', '.join(f'`{m}`' for m in f.measures)}")
        if f.foreign_keys:
            lines.append("- **Foreign Keys**:")
            for col, tgt in f.foreign_keys.items():
                lines.append(f"    - `{col}` → `{tgt}`")
        if f.reasoning:
            lines.append("")
            lines.append("**Why This Was Proposed**")
            lines.append("")
            lines.append(f.reasoning)
        if f.evidence_sources:
            lines.append("")
            lines.append("**Evidence**")
            for ev in f.evidence_sources:
                lines.append(f"- {ev}")
        if f.needs_user_confirmation:
            lines.append("")
            lines.append("> **Needs user confirmation** — grain and measure list are agent proposals.")
        lines.append("")

    lines.append("## Dimensions")
    lines.append("")
    if not schema.dimensions:
        lines.append("_No dimension tables defined yet._")
        lines.append("")
    for d in schema.dimensions:
        lines.append(f"### `dim_{d.name}`" if not d.name.startswith("dim_") else f"### `{d.name}`")
        lines.append("")
        lines.append(f"- **SCD Type**: {d.scd_type}")
        if d.natural_key:
            lines.append(f"- **Natural Key**: {', '.join(f'`{k}`' for k in d.natural_key)}")
        if d.surrogate_key:
            lines.append(f"- **Surrogate Key**: `{d.surrogate_key}`")
        if d.source_silver_tables:
            lines.append(f"- **Source Silver tables**: {', '.join(f'`{s}`' for s in d.source_silver_tables)}")
        if d.attributes:
            lines.append(f"- **Attributes**: {', '.join(f'`{a}`' for a in d.attributes)}")
        if d.is_conformed:
            lines.append("- **Conformed dimension** (shared across multiple facts)")
        if d.reasoning:
            lines.append("")
            lines.append("**Why This Was Proposed**")
            lines.append("")
            lines.append(d.reasoning)
        if d.evidence_sources:
            lines.append("")
            lines.append("**Evidence**")
            for ev in d.evidence_sources:
                lines.append(f"- {ev}")
        if d.needs_user_confirmation:
            lines.append("")
            lines.append("> **Needs user confirmation** — SCD type and natural key are agent proposals.")
        lines.append("")

    lines.append("## Relationships")
    lines.append("")
    if not schema.relationships:
        lines.append("_No inter-table relationships declared yet._")
        lines.append("")
    else:
        lines.append("| From | To | Cardinality | Confidence | Evidence | Status |")
        lines.append("|---|---|---|---|---|---|")
        for r in schema.relationships:
            ev = "; ".join(r.evidence) if r.evidence else "_none_"
            status = "needs confirmation" if r.needs_user_confirmation else "confirmed"
            lines.append(
                f"| `{r.from_table}.{r.from_column}` | `{r.to_table}.{r.to_column}` "
                f"| {r.cardinality} | {r.confidence:.2f} | {ev} | {status} |"
            )
        lines.append("")

    if schema.open_questions:
        lines.append("## Remaining Risk / Open Questions")
        lines.append("")
        for q in schema.open_questions:
            lines.append(f"- {q}")
        lines.append("")

    return "\n".join(lines) + "\n"


# ── silver contract ────────────────────────────────────────────────────────────

def render_silver_contract_md(contract: SilverContract) -> str:
    lines: list[str] = []
    lines.append(f"# Silver Contract — {contract.workspace}")
    lines.append("")
    lines.append("Generated by the Medallion Architect. Source of truth is `silver_contract.json`.")
    lines.append("This document is regenerated; do not hand-edit.")
    lines.append("")

    if not contract.tables:
        lines.append("_No Silver tables defined yet._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for name in sorted(contract.tables.keys()):
        lines.extend(_render_table_contract_md(name, contract.tables[name]))
    return "\n".join(lines) + "\n"


def _render_table_contract_md(name: str, tc: TableContract) -> list[str]:
    lines: list[str] = [f"## `silver.{name}`", ""]

    if tc.type_casts:
        lines.append("### Type Casts")
        lines.append("")
        lines.append("| Column | From | To | Format |")
        lines.append("|---|---|---|---|")
        for col, cast in tc.type_casts.items():
            fmt = cast.format or "—"
            lines.append(f"| `{col}` | {cast.from_type} | {cast.to_type} | {fmt} |")
        lines.append("")

    if tc.null_policies:
        lines.append("### Null Policies")
        lines.append("")
        lines.append("| Column | Policy |")
        lines.append("|---|---|")
        for col, np in tc.null_policies.items():
            lines.append(f"| `{col}` | `{np.to_str()}` |")
        lines.append("")

    if tc.dedup_keys:
        lines.append(f"**Dedup keys**: {', '.join(f'`{k}`' for k in tc.dedup_keys)}")
        lines.append("")

    if tc.pii_hash_columns:
        lines.append(f"**PII (hashed via `{tc.hash_salt_ref}`)**: {', '.join(f'`{c}`' for c in tc.pii_hash_columns)}")
        lines.append("")

    if tc.derived_columns:
        lines.append("### Derived Columns")
        lines.append("")
        for col_name, dc in tc.derived_columns.items():
            lines.append(f"#### `{col_name}`")
            lines.append("")
            if dc.business_meaning:
                lines.append(f"_{dc.business_meaning}_")
                lines.append("")
            ft = dc.formula_templates
            if ft.duckdb_sql:
                lines.append("**DuckDB**")
                lines.append("")
                lines.append("```sql")
                lines.append(ft.duckdb_sql)
                lines.append("```")
                lines.append("")
            if ft.spark_sql:
                lines.append("**Spark SQL**")
                lines.append("")
                lines.append("```sql")
                lines.append(ft.spark_sql)
                lines.append("```")
                lines.append("")
            if ft.polars:
                lines.append("**Polars**")
                lines.append("")
                lines.append("```python")
                lines.append(ft.polars)
                lines.append("```")
                lines.append("")
            if dc.input_columns:
                lines.append("**Inputs**")
                lines.append("")
                lines.append("| Column | Dataset | Role | Dtype |")
                lines.append("|---|---|---|---|")
                for ic in dc.input_columns:
                    lines.append(f"| `{ic.column}` | `{ic.dataset}` | {ic.role} | {ic.dtype} |")
                lines.append("")
            if dc.reasoning:
                lines.append("**Why This Was Proposed**")
                lines.append("")
                lines.append(dc.reasoning)
                lines.append("")
            if dc.source_review:
                lines.append(f"**Source review**: `{dc.source_review}`")
                lines.append("")
            if dc.computed_once_reused_by_kpis:
                lines.append(f"**Reused by KPIs**: {', '.join(f'`{k}`' for k in dc.computed_once_reused_by_kpis)}")
                lines.append("")

    if tc.assertions:
        lines.append("### Assertions (post-load checks)")
        lines.append("")
        lines.append("| ID | Type | Details |")
        lines.append("|---|---|---|")
        for a in tc.assertions:
            details = _assertion_details(a)
            lines.append(f"| `{a.id}` | `{a.type}` | {details} |")
        lines.append("")

    return lines


def _assertion_details(a) -> str:
    parts: list[str] = []
    if a.columns:
        parts.append("cols=" + ",".join(f"`{c}`" for c in a.columns))
    if a.tolerance_pct is not None:
        parts.append(f"tolerance={a.tolerance_pct}%")
    if a.child:
        parts.append(f"child=`{a.child}`")
    if a.parent:
        parts.append(f"parent=`{a.parent}`")
    if a.property:
        parts.append(f"property=`{a.property}`")
    return " · ".join(parts) if parts else "—"


# ── lineage ────────────────────────────────────────────────────────────────────

def render_lineage_md(lineage: Lineage) -> str:
    lines: list[str] = []
    lines.append(f"# Lineage — {lineage.workspace}")
    lines.append("")
    lines.append("Generated by the Medallion Architect. Source of truth is `lineage.json`.")
    lines.append("This document is regenerated; do not hand-edit.")
    lines.append("")

    by_layer: dict[str, list] = {"bronze": [], "silver": [], "gold": []}
    for n in lineage.nodes:
        by_layer.setdefault(n.layer, []).append(n)
    for layer in ("bronze", "silver", "gold"):
        lines.append(f"## {layer.capitalize()} Nodes")
        lines.append("")
        nodes = by_layer.get(layer, [])
        if not nodes:
            lines.append("_None._")
            lines.append("")
            continue
        for n in sorted(nodes, key=lambda x: x.table):
            cols = ", ".join(f"`{c}`" for c in n.columns) if n.columns else "_(columns not declared)_"
            lines.append(f"- `{n.qualified}` — {cols}")
        lines.append("")

    lines.append("## Edges (column-level)")
    lines.append("")
    if not lineage.edges:
        lines.append("_No edges declared._")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append("| From node | From columns | To node | To columns | Transform | Reasoning |")
    lines.append("|---|---|---|---|---|---|")
    for e in lineage.edges:
        fc = ", ".join(f"`{c}`" for c in e.from_columns) if e.from_columns else "—"
        tc = ", ".join(f"`{c}`" for c in e.to_columns) if e.to_columns else "—"
        rsn = e.reasoning if e.reasoning else "—"
        lines.append(f"| `{e.from_node}` | {fc} | `{e.to_node}` | {tc} | `{e.transform_type}` | {rsn} |")
    lines.append("")

    lines.append("## Gold Column Traces")
    lines.append("")
    gold_nodes = [n for n in lineage.nodes if n.layer == "gold"]
    if not gold_nodes:
        lines.append("_No Gold nodes declared._")
        lines.append("")
        return "\n".join(lines) + "\n"

    for node in sorted(gold_nodes, key=lambda x: x.table):
        lines.append(f"### `{node.qualified}`")
        lines.append("")
        columns = list(node.columns)
        if not columns:
            columns = sorted({
                col
                for edge in lineage.edges
                if edge.to_node == node.qualified
                for col in edge.to_columns
            })
        if not columns:
            lines.append("_No Gold columns declared._")
            lines.append("")
            continue
        lines.append("| Gold column | Bronze source columns |")
        lines.append("|---|---|")
        for column in columns:
            sources = lineage.trace_to_sources("gold", node.table, column)
            source_text = ", ".join(f"`{src}.{col}`" for src, col in sources) if sources else "—"
            lines.append(f"| `{column}` | {source_text} |")
        lines.append("")
    return "\n".join(lines) + "\n"
