"""
core/medallion/delta_emitter.py — Spark/Delta PySpark file emitter (P2).

Emits *.spark.py siblings for every Bronze, Silver, Gold table. These files
are generated in design-medallion and executed via JobsBackend/ConnectBackend
when --target delta is passed to build-medallion.
"""
from __future__ import annotations

from pathlib import Path

from core.medallion.manifest import BronzeTable, SilverTable, GoldTable
from core.medallion.pii import pii_hash_spark_expr
from core.medallion.silver_contract import SilverContract
from core.sql_safety import assert_safe_identifier, validate_expression_safe


def uc_schema_for(workspace: str, layer: str) -> str:
    """Normalize workspace name to a Unity Catalog schema name."""
    normalized = workspace.lower().replace("-", "_").replace(" ", "_")
    return f"{normalized}_medallion_{layer}"


def emit_bronze_spark(
    table: BronzeTable,
    out_dir: Path,
    workspace_name: str,
    repo_root: Path,
    workspace: Path,
) -> Path:
    bronze_schema = uc_schema_for(workspace_name, "bronze")
    target = f"{bronze_schema}.{table.name}"

    # Build a DBFS-style source path (users must map this to their mount)
    try:
        rel = Path(table.source_file).relative_to(repo_root)
        source_path = f"dbfs:/mnt/data/{rel.as_posix()}"
    except ValueError:
        source_path = f"dbfs:/mnt/data/{Path(table.source_file).name}"

    code = f'''"""bronze.{table.name} — generated by Medallion Architect (P2).

Do not hand-edit. Regenerate via `uv run medallion design`.
"""
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.getOrCreate()

SOURCE_PATH = "{source_path}"
TARGET = "{target}"

spark.sql("CREATE SCHEMA IF NOT EXISTS {bronze_schema}")

(
    spark.read
         .option("header", True)
         .option("inferSchema", True)
         .csv(SOURCE_PATH)
         .withColumn("_source_system", F.lit("{table.source_system}"))
         .withColumn("_source_file", F.lit(SOURCE_PATH))
         .withColumn("_load_ts", F.current_timestamp())
         .write
         .format("delta")
         .mode("append")
         # Bronze stays SCHEMA-FLEXIBLE: an upstream column added later is
         # captured here without failing the load (Step 6: schema evolution).
         .option("mergeSchema", "true")
         .saveAsTable(TARGET)
)
'''
    path = out_dir / f"{table.name}.spark.py"
    path.write_text(code, encoding="utf-8")
    return path


def emit_silver_spark(
    table: SilverTable,
    out_dir: Path,
    workspace_name: str,
    contract: SilverContract,
) -> Path:
    silver_schema = uc_schema_for(workspace_name, "silver")
    bronze_schema = uc_schema_for(workspace_name, "bronze")
    target = f"{silver_schema}.{table.name}"

    # PK merge condition. Validate every PK name as a bare identifier so a
    # malformed/hostile contract cannot inject SQL into the emitted MERGE
    # (T4). Valid names pass through unchanged; bad names fail the build.
    pk_cols = [
        assert_safe_identifier(col, context="silver PK column")
        for col in table.primary_key
    ]
    pk_condition = " AND ".join(
        f"tgt.{col} = src.{col}" for col in pk_cols
    ) or "tgt._load_ts = src._load_ts"

    # Source tables
    sources_list = "[\n" + "".join(
        f'    ("{bronze_schema}.{src.split(".", 1)[-1]}", "{_source_system_from(src)}"),\n'
        for src in table.derived_from
    ) + "]"

    # Derived columns
    tc = (contract.tables or {}).get(table.name)
    derived_lines = ""
    if tc:
        for dname, dc in tc.derived_columns.items():
            spark_expr = dc.formula_templates.spark_sql or ""
            if spark_expr:
                # Validate the derived column name as an identifier and the
                # workspace-owned formula body for injection markers, then embed
                # the body via repr() so any embedded quote/backslash cannot
                # break out of the F.expr(...) string (T4).
                assert_safe_identifier(dname, context="derived column name")
                validate_expression_safe(spark_expr, context="derived spark_sql formula")
                derived_lines += (
                    f'\nsource_df = source_df.withColumn("{dname}", F.expr({spark_expr!r}))'
                )

    pii_lines = ""
    if tc:
        for col in tc.pii_hash_columns:
            # Validate the column name; the hash expression is generated from it
            # by pii_hash_spark_expr, so a validated name yields a safe expr.
            assert_safe_identifier(col, context="pii hash column")
            pii_lines += (
                f'\nsource_df = source_df.withColumn('
                f'"{col}", F.expr("{pii_hash_spark_expr(col)}")'
                f')  # PII: salted workspace hash'
            )

    code = f'''"""silver.{table.name} — MERGE-on-PK generated by Medallion Architect (P2).

Do not hand-edit. Regenerate via `uv run medallion design`.
"""
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from delta.tables import DeltaTable

spark = SparkSession.builder.getOrCreate()

def _workspace_salt():
    try:
        return dbutils.secrets.get(scope="autoresearch", key="medallion_salt__{workspace_name}")  # noqa: F821
    except Exception as exc:
        raise RuntimeError(
            "Missing Databricks secret autoresearch/medallion_salt__{workspace_name}"
        ) from exc

spark.udf.register("get_workspace_salt", _workspace_salt, "string")

TARGET = "{target}"
SOURCES = {sources_list}

spark.sql("CREATE SCHEMA IF NOT EXISTS {silver_schema}")

source_df = None
for table_name, sys_name in SOURCES:
    df = spark.table(table_name).withColumn("source_system", F.lit(sys_name))
    source_df = df if source_df is None else source_df.unionByName(df, allowMissingColumns=True)
{derived_lines}{pii_lines}

if not spark.catalog.tableExists(TARGET):
    source_df.limit(0).write.format("delta").saveAsTable(TARGET)

DeltaTable.forName(spark, TARGET).alias("tgt").merge(
    source_df.alias("src"),
    "{pk_condition}",
).whenMatchedUpdateAll().whenNotMatchedInsertAll().execute()
'''
    path = out_dir / f"{table.name}.spark.py"
    path.write_text(code, encoding="utf-8")
    return path


def emit_gold_spark(
    table: GoldTable,
    out_dir: Path,
    workspace_name: str,
) -> Path:
    gold_schema = uc_schema_for(workspace_name, "gold")
    silver_schema = uc_schema_for(workspace_name, "silver")
    target = f"{gold_schema}.{table.name}"

    # Derive Silver source tables
    source_tables = [
        f"{silver_schema}.{src.split('.', 1)[-1]}" for src in table.derived_from
    ]
    first_source = source_tables[0] if source_tables else f"{silver_schema}.unknown"

    code = f'''"""gold.{table.name} — full-refresh generated by Medallion Architect (P2).

Do not hand-edit. Regenerate via `uv run medallion design`.
"""
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

TARGET = "{target}"

spark.sql("CREATE SCHEMA IF NOT EXISTS {gold_schema}")

df = spark.table("{first_source}")
df.write.format("delta").mode("overwrite").saveAsTable(TARGET)
'''
    path = out_dir / f"{table.name}.spark.py"
    path.write_text(code, encoding="utf-8")
    return path


def emit_gold_duckdb(table: GoldTable, out_dir: Path) -> Path:
    """Emit the DuckDB Gold SQL.

    A fact with proven foreign keys is denormalised into a wide One-Big-Table
    (OBT): the fact LEFT JOINed to each dimension, with the dimension's non-key
    columns prefixed (``<dim>_<col>``) to avoid collisions. The join happens ONCE
    here so dashboards scan a flat table with no runtime joins. A fact without
    FKs (or a dimension) stays a full-refresh copy.
    """
    first_silver = (
        f"silver.{table.derived_from[0].split('.', 1)[-1]}"
        if table.derived_from else "silver.unknown"
    )
    fks = getattr(table, "foreign_keys", None) or []
    if table.kind == "fact" and fks:
        joins: list[str] = []
        select_cols = ["f.*"]
        for i, fk in enumerate(fks):
            dim_silver = f"silver.{str(fk['to_table']).split('.', 1)[-1]}"
            dim_entity = dim_silver.split(".", 1)[-1]
            alias = f"d{i}"
            fcol = assert_safe_identifier(str(fk["from_column"]), context="gold OBT fk col")
            tcol = assert_safe_identifier(str(fk["to_column"]), context="gold OBT to col")
            joins.append(
                f"LEFT JOIN {dim_silver} {alias} ON f.\"{fcol}\" = {alias}.\"{tcol}\"")
            # Prefix the dimension's columns so a flat OBT has no name clashes.
            # COLUMNS(...) excludes the join key (already on the fact).
            select_cols.append(
                f"{alias}.* EXCLUDE (\"{tcol}\")")
        sql = (
            f"-- gold.{table.name}: OBT (fact silver.{table.derived_from[0].split('.',1)[-1]} "
            f"pre-joined with {len(fks)} dimension(s))\n"
            f"CREATE OR REPLACE TABLE gold.{table.name} AS\n"
            f"SELECT {', '.join(select_cols)}\n"
            f"FROM {first_silver} f\n"
            + "\n".join(joins) + ";\n"
        )
    elif table.kind == "dimension" and table.scd_type == 2:
        # SCD Type 2: track history with valid_from/valid_to via the shared
        # idempotent emitter. Business key = the dimension's canonical PK (the
        # first derived-from silver table's <entity>_id).
        from core.medallion.merge_emitter import emit_scd2_merge

        entity = table.derived_from[0].split(".", 1)[-1] if table.derived_from else table.name
        bk = f"{entity}_id"
        # All non-key columns are tracked attributes; emit a SELECT * body and let
        # the merge close/insert on change. (Attribute list resolved at build from
        # the silver schema; here we pass the canonical key + a star body.)
        body = f"SELECT * FROM {first_silver}"
        sql = (
            f"-- gold.{table.name}: SCD Type 2 (history via valid_from/valid_to)\n"
            f"-- Build resolves tracked attributes from the silver schema.\n"
            + emit_scd2_merge(table.name, [bk], [], body, schema="gold")
        )
    else:
        sources = ", ".join(f"silver.{src.split('.', 1)[-1]}" for src in table.derived_from)
        sql = (
            f"-- gold.{table.name}: full-refresh {table.kind} from {sources}\n"
            f"CREATE OR REPLACE TABLE gold.{table.name} AS\n"
            f"SELECT * FROM {first_silver};\n"
        )
    path = out_dir / f"{table.name}.duckdb.sql"
    path.write_text(sql, encoding="utf-8")
    return path


def _source_system_from(src: str) -> str:
    if "__" in src:
        return src.rsplit("__", 1)[-1]
    return src.split(".", 1)[-1] if "." in src else src
