"""run-ingestion: gated execution of generated COPY INTO / Auto Loader jobs.

F17 -- `generate-ingestion` emitted 12 runnable jobs and the platform had no
governed way to run them, so landing data meant reaching for the raw vendor CLI
and routing around AUTORESEARCH_ALLOW_REMOTE_EXECUTION. These tests pin the same
refusal ladder `apply-provisioning` already proves.
"""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from core.onboarding.workspace.delegation import routing_for
from core.provisioning.ingestion_run import (
    STATUS_DRY_RUN,
    STATUS_EXECUTED,
    STATUS_FAILED,
    STATUS_REFUSED_KILL_SWITCH,
    STATUS_REFUSED_NO_CONFIRMATION,
    STATUS_REFUSED_UNAVAILABLE,
    run_ingestion_jobs,
    sql_statements,
)

MANIFEST = {
    "artifact_type": "ingestion/jobs_manifest.json",
    "version": 1,
    "workspace": "demo",
    "connector": "s3",
    "catalog": "demo_dev",
    "bronze_schema": "bronze",
    "credential_ref": "cred_x",
    "additive_only": True,
    "job_count": 2,
    "blocked_count": 0,
    "jobs": [
        {
            "job_name": "ingest_a", "table": "a", "method": "copy_into",
            "status": "emitted", "file": "ingestion/ingest_a.sql",
            "target_table": "demo_dev.bronze.a", "format": "csv",
        },
        {
            "job_name": "ingest_b", "table": "b", "method": "copy_into",
            "status": "emitted", "file": "ingestion/ingest_b.sql",
            "target_table": "demo_dev.bronze.b", "format": "csv",
        },
    ],
}

JOB_SQL = """-- COPY INTO ingestion for {name}.
-- Generated by `generate-ingestion` -- edit the generator, not this file.

CREATE TABLE IF NOT EXISTS demo_dev.bronze.{name};

COPY INTO demo_dev.bronze.{name}
FROM 's3://bkt/pfx/{name}'
FILEFORMAT = CSV
COPY_OPTIONS ('mergeSchema' = 'true');
"""


class FakeRunner:
    """Records every statement; `fail_on` raises for a matching fragment."""

    def __init__(self, fail_on: str = ""):
        self.statements: list[str] = []
        self.fail_on = fail_on

    def execute(self, sql: str) -> None:
        self.statements.append(sql)
        if self.fail_on and self.fail_on in sql:
            raise RuntimeError("warehouse said no")


def _workspace(tmp: str, *, confirmed: bool) -> tuple[Path, str]:
    root = Path(tmp)
    ws_rel = "workspaces/demo"
    ws = root / ws_rel
    (ws / "ingestion").mkdir(parents=True, exist_ok=True)
    (ws / "ingestion" / "jobs_manifest.json").write_text(
        json.dumps(MANIFEST), encoding="utf-8"
    )
    for name in ("a", "b"):
        (ws / "ingestion" / f"ingest_{name}.sql").write_text(
            JOB_SQL.format(name=name), encoding="utf-8"
        )
    if confirmed:
        marker = ws / "interns" / "reports" / "solution_blueprint"
        marker.mkdir(parents=True, exist_ok=True)
        (marker / "current.confirmed.json").write_text(
            json.dumps({"confirmed_by": "a human", "status": "confirmed"}),
            encoding="utf-8",
        )
    return root, ws_rel


def _log(root: Path, ws_rel: str) -> dict:
    return json.loads(
        (root / ws_rel / "interns/generated/evidence/ingestion/run_log.json").read_text()
    )


class StatementSplitTests(unittest.TestCase):
    def test_comments_are_stripped_and_statements_split(self):
        found = sql_statements(JOB_SQL.format(name="a"))
        self.assertEqual(len(found), 2)
        self.assertTrue(found[0].startswith("CREATE TABLE IF NOT EXISTS"))
        self.assertTrue(found[1].startswith("COPY INTO"))
        self.assertNotIn("--", " ".join(found))

    def test_trailing_whitespace_yields_no_empty_statement(self):
        self.assertEqual(sql_statements("SELECT 1;\n\n   \n"), ["SELECT 1"])

    def test_empty_text_is_no_statements(self):
        self.assertEqual(sql_statements("-- only a comment\n"), [])


class GateTests(unittest.TestCase):
    def test_without_confirmation_it_is_a_dry_run_and_runs_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=False)
            runner = FakeRunner()
            result = run_ingestion_jobs(root, ws, runner=runner)
            self.assertEqual(result.status, STATUS_REFUSED_NO_CONFIRMATION)
            self.assertFalse(result.ok)
            self.assertEqual(runner.statements, [])
            self.assertEqual(_log(root, ws)["counts"]["executed"], 0)

    def test_kill_switch_refuses_even_when_confirmed(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            runner = FakeRunner()
            with mock.patch.dict(
                "os.environ", {"AUTORESEARCH_ALLOW_REMOTE_EXECUTION": "0"}, clear=False
            ):
                result = run_ingestion_jobs(root, ws, runner=runner)
            self.assertEqual(result.status, STATUS_REFUSED_KILL_SWITCH)
            self.assertFalse(result.ok)
            self.assertEqual(runner.statements, [])

    def test_explicit_dry_run_when_confirmed_runs_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            runner = FakeRunner()
            result = run_ingestion_jobs(root, ws, dry_run=True, runner=runner)
            self.assertEqual(result.status, STATUS_DRY_RUN)
            self.assertTrue(result.ok)
            self.assertEqual(runner.statements, [])
            self.assertTrue(all(j["status"] == "would_execute" for j in result.jobs))

    def test_warehouse_unreachable_is_a_structured_failure(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            with mock.patch(
                "core.provisioning.ingestion_run._sdk_runner",
                side_effect=ConnectionError("no warehouse"),
            ):
                result = run_ingestion_jobs(root, ws)
            self.assertEqual(result.status, STATUS_REFUSED_UNAVAILABLE)
            self.assertFalse(result.ok)
            self.assertIn("check-platform-readiness", result.next_command)
            self.assertEqual(result.executed, 0)


class ExecutionTests(unittest.TestCase):
    def test_confirmed_run_executes_every_job_in_order(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            runner = FakeRunner()
            result = run_ingestion_jobs(root, ws, runner=runner)
            self.assertEqual(result.status, STATUS_EXECUTED)
            self.assertTrue(result.ok)
            self.assertEqual(result.executed, 2)
            self.assertEqual(result.failed, 0)
            # two statements per job, jobs in manifest order
            self.assertEqual(len(runner.statements), 4)
            self.assertIn("demo_dev.bronze.a", runner.statements[0])
            self.assertIn("demo_dev.bronze.b", runner.statements[2])

    def test_failure_stops_and_remaining_jobs_are_not_attempted(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            runner = FakeRunner(fail_on="demo_dev.bronze.a")
            result = run_ingestion_jobs(root, ws, runner=runner)
            self.assertEqual(result.status, STATUS_FAILED)
            self.assertFalse(result.ok)
            self.assertEqual(result.failed, 1)
            statuses = [j["status"] for j in result.jobs]
            self.assertEqual(statuses, ["failed", "not_attempted"])
            self.assertNotIn("demo_dev.bronze.b", " ".join(runner.statements))

    def test_rerun_is_safe_because_copy_into_is_idempotent(self):
        # COPY INTO skips files it already ingested, so a second run is a
        # legitimate no-op at the warehouse; the command must not refuse it.
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            runner = FakeRunner()
            run_ingestion_jobs(root, ws, runner=runner)
            second = run_ingestion_jobs(root, ws, runner=runner)
            self.assertEqual(second.status, STATUS_EXECUTED)
            self.assertEqual(len(runner.statements), 8)

    def test_missing_manifest_refuses(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "workspaces" / "empty" / "interns").mkdir(parents=True)
            with self.assertRaises(FileNotFoundError):
                run_ingestion_jobs(root, "workspaces/empty", runner=FakeRunner())


class RunLogTests(unittest.TestCase):
    def test_log_shape_and_no_secret_values(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            result = run_ingestion_jobs(root, ws, runner=FakeRunner())
            log = _log(root, ws)
            self.assertEqual(log["artifact_type"], "evidence/ingestion/run_log.json")
            self.assertTrue(log["confirmed_blueprint"])
            self.assertEqual(log["catalog"], "demo_dev")
            self.assertEqual(
                set(log["counts"]), {"executed", "failed", "not_attempted", "blocked"}
            )
            self.assertEqual(len(log["jobs"]), len(result.jobs))
            raw = json.dumps(log).lower()
            for word in ("password", "token", "secret_value", "akia"):
                self.assertNotIn(word, raw)


class StageRoutingTests(unittest.TestCase):
    def test_summary_carries_the_ingestion_roster(self):
        with tempfile.TemporaryDirectory() as tmp:
            root, ws = _workspace(tmp, confirmed=True)
            summary = run_ingestion_jobs(root, ws, runner=FakeRunner()).summary()
            roster = routing_for("ingestion_generation")
            self.assertTrue(roster["agents"], "ingestion routes no agent")
            self.assertEqual(summary["stage"], "ingestion_generation")
            self.assertEqual(summary["required_specialists"], roster["agents"])
            self.assertEqual(summary["suggested_skills"], roster["skills"])


if __name__ == "__main__":
    unittest.main()
