"""Detect a generated artifact that is older than the code that generates it.

The 2026-07-27 verification found `workspaces/rcm_dashboard/dbt` still carrying
the KPI-002 identifier leak, a `CURRENT_DATE` that Phase 0 had pinned months
earlier, and a `query_tags` with no `run_id`. None of those were live bugs --
every fix was in `core/`. The artifact on disk simply predated all of them, and
nothing anywhere noticed.

Incremental onboarding fingerprints INPUTS (datasets, KPI registry, data model,
recorded decisions), so an unchanged dataset means "still current" no matter how
far the generator has moved. That is the gap: a generator fix silently fails to
reach any workspace that is not otherwise dirty.

So each generator stamps the CONTENT hash of its own modules when it writes, and
the workspace validator recomputes and compares. Content, not mtime -- the
mid-run drift check in `flow._core_tree_fingerprint` stats for speed, which is
right for "did this change in the last 90 seconds" and wrong here: a fresh clone
rewrites every mtime and would report every artifact stale.

Scoped per artifact family, not to the whole tree. Hashing all of `core/` would
mean any commit anywhere invalidated every artifact, the warning would be
permanent, and a permanent warning is one nobody reads.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
from typing import Any

from core.storage.workspace_layout import WorkspaceLayout

STAMP_FILENAME = "generator_stamps.json"

# artifact family -> the modules whose output it IS. Add a family when a
# generator's output is persisted and re-read later; list only the modules that
# actually shape the bytes on disk, or the stamp turns into tree-wide noise.
GENERATOR_MODULES: dict[str, tuple[str, ...]] = {
    "dbt_project": (
        "core.onboarding.kpi.dbt_project_generator",
        "core.onboarding.kpi.sql_generator",
        "core.onboarding.kpi.result_view_builder",
    ),
    "kpi_sql": (
        "core.onboarding.kpi.sql_generator",
        "core.onboarding.kpi.result_view_builder",
    ),
}


def fingerprint(modules: tuple[str, ...]) -> str:
    """Content hash of the named modules' source files.

    A module that cannot be located contributes its name and nothing else --
    a rename then shows up as a changed fingerprint, which is the honest answer
    (the artifact WAS generated by different code).
    """
    digest = hashlib.sha256()
    for name in sorted(modules):
        digest.update(name.encode())
        try:
            spec = importlib.util.find_spec(name)
            origin = spec.origin if spec else None
        except (ImportError, ValueError):
            origin = None
        if not origin:
            continue
        try:
            digest.update(Path(origin).read_bytes())
        except OSError:
            continue
    return digest.hexdigest()[:16]


def _stamp_path(layout: WorkspaceLayout) -> Path:
    return layout.state_dir / STAMP_FILENAME


def _load(layout: WorkspaceLayout) -> dict[str, Any]:
    path = _stamp_path(layout)
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return data.get("artifacts", {}) if isinstance(data, dict) else {}


def stamp(layout: WorkspaceLayout, artifact: str) -> str:
    """Record the generator fingerprint for `artifact`. Returns it."""
    modules = GENERATOR_MODULES.get(artifact)
    if not modules:
        raise KeyError(
            f"unknown artifact family {artifact!r}; add it to GENERATOR_MODULES "
            "with the modules that shape its bytes."
        )
    current = fingerprint(modules)
    artifacts = _load(layout)
    artifacts[artifact] = {"fingerprint": current, "modules": list(modules)}
    path = _stamp_path(layout)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps({"artifact_type": "generator_stamps", "version": 1,
                    "artifacts": artifacts}, indent=2) + "\n",
        encoding="utf-8",
    )
    return current


def stale(layout: WorkspaceLayout) -> list[dict[str, str]]:
    """Artifact families generated by code that has since changed.

    Only families with a recorded stamp are reported. An artifact generated
    before stamping existed has no stamp and is not flagged here -- that is
    `unstamped`'s job, and conflating "we know it is old" with "we cannot tell"
    would make the first claim untrustworthy.
    """
    out: list[dict[str, str]] = []
    for artifact, record in sorted(_load(layout).items()):
        modules = GENERATOR_MODULES.get(artifact)
        if not modules:
            continue
        current = fingerprint(modules)
        recorded = str(record.get("fingerprint") or "")
        if recorded and recorded != current:
            out.append({
                "artifact": artifact,
                "generated_by": recorded,
                "current": current,
                "modules": ", ".join(modules),
            })
    return out


def unstamped(layout: WorkspaceLayout, present: dict[str, bool]) -> list[str]:
    """Families whose artifact EXISTS on disk but carries no stamp at all.

    `present` maps family -> does its output exist. This is the case that let
    `rcm_dashboard` ship a months-old dbt project: age unknown, so nothing to
    compare, so silence. Reported as its own finding rather than folded into
    `stale`, because the remedy is the same (regenerate) but the confidence is not.
    """
    recorded = _load(layout)
    return sorted(
        family for family, exists in present.items()
        if exists and family in GENERATOR_MODULES and family not in recorded
    )
