"""Workflow guardrail harness for agent/tool failures.

This harness catches failures that happen around the governed tools rather than
inside generated KPI SQL: unsupported shell commands, raw-data reads that bypass
profiles, and blocker panels that ask about invented or non-source-backed
features.
"""
from __future__ import annotations

import argparse
import json
import re
import shlex
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.onboarding.harness.trajectory_recorder import load_trajectory
from core.presentation.console_tables import render_markdown_table
from core.storage.workspace_layout import WorkspaceLayout


HARNESS_VERSION = 1
WINDOWS_UNIX_COMMANDS = {"cat", "head", "tail", "grep", "sed", "awk", "cp", "mv", "rm", "ln"}
RAW_DATA_READ_COMMANDS = {"cat", "type", "get-content", "import-csv"}
DATA_SUFFIXES = {".csv", ".parquet", ".json", ".jsonl", ".xlsx", ".xls"}
GENERIC_TEMPORAL_PLACEHOLDERS = {"created_at", "updated_at", "timestamp", "event_time"}
SLOW_STEP_THRESHOLD_MS = 120000
# Per-stage wall-clock budget for a single recorded command (seconds). A
# deterministic stage tool should finish well under this; a longer run points at
# a hung/runaway invocation.
STAGE_TIME_BUDGET_SECONDS = 30
# Workflow-route commands that require the agent to have read the tool registry
# (.agents/**/SKILLS.md) first so it picks the right route for the workspace.
WORKFLOW_ROUTE_TOKENS = (
    "resolve-kpi-features", "prepare-kpi-generation", "prepare-kpi-blocker-panel",
    "build-source-family-contracts", "run-data-engineering-route",
)
# KPI-generation/resolution routes that are WRONG for an external-source
# workspace (which must go through the source-catalog/source-family route first).
KPI_ROUTE_TOKENS = (
    "resolve-kpi-features", "prepare-kpi-generation", "prepare-kpi-blocker-panel",
    "generate-pipeline-sql",
)
# Generic shell, git, and runner executables that are always allowed regardless of
# the project tool roster. Kept domain-agnostic on purpose.
GENERIC_COMMANDS = {
    "git", "uv", "python", "python3", "py", "pip", "ruff", "pytest",
    "rg", "ls", "dir", "cd", "echo", "type", "get-content", "get-childitem",
    "select-object", "select-string", "measure-object", "where-object",
    "foreach-object", "test-path", "new-item", "remove-item", "set-content",
    "out-file", "mkdir", "node", "npm", "npx", "pwsh", "powershell", "bash",
    "sh", "cmd", "set-location",
}
# Workflow stages that mean the session is still awaiting work / not terminal.
TERMINAL_STAGE_KEYWORDS = ("complete", "done", "finished", "closed", "passed", "terminal")
AWAITING_STAGE_KEYWORDS = ("await", "pending", "blocked", "needs_", "in_progress", "waiting")
# A deterministic command run this many times (after normalization) in one
# session is treated as a redundant re-run rather than legitimate retry.
REPEATED_COMMAND_THRESHOLD = 3
# Directory fragments whose contents are generated by the engine and overwritten
# on regeneration; a hand-edit here is lost on the next run. Kept workspace-agnostic.
GENERATED_ARTIFACT_DIRS = (
    "interns/generated/solutions/",
    "interns/generated/contracts/",
    "interns/generated/profiles/",
)
# Event types that represent the agent writing/editing a file (as opposed to
# running a CLI command). Matched case-insensitively, substring-wise.
FILE_MUTATION_EVENT_TYPES = ("write", "edit", "create_file", "file_write", "file_edit")
# Volatile command fragments that should be ignored when deciding whether two
# commands are "the same" deterministic invocation.
_VOLATILE_COMMAND_FLAGS = ("--quiet", "--verbose", "--diff", "--render-only")
# Recognizes a throwaway one-off reader script created at the repo root, e.g.
# read_panel.py / read_results.py.
_READER_SCRIPT_RE = re.compile(r"(?:^|[\\/])(read_[a-z0-9_]*\.py)$", re.IGNORECASE)
# Tokens that mark a step as a *mutation* (an apply/answer/finalize/commit-style op
# that changes workspace state). A failed mutation that is never retried/recovered
# is the one that must not be papered over by a later completion claim. Generic and
# structural -- matched on the invoked tool/command verb, not on any domain.
MUTATION_COMMAND_TOKENS = (
    "apply-", "apply_", "finalize-", "finalize_", "answer", "confirm", "commit",
)
# Tokens that mark a step as a *completion / results / proof* claim -- the point at
# which the workflow asserts work is done and emits results. Read from the command,
# event_type, status, or summary so the signal survives whichever surface carries
# it. Kept domain-agnostic (no workspace/tool vocabulary).
COMPLETION_CLAIM_TOKENS = (
    "run-kpi-pipeline", "kpi-results", "kpi_results", "results", "proof",
    "proven", "complete", "completed", "finalized", "fully",
)
# Recovery is a retry of the *same operation* or an explicit recovery/validation
# routing -- NOT merely "some other uv-run command followed". A completion/results
# claim is a `uv run ...` too, so the bare "uv run " heuristic must never count it
# as recovery. These are the tool verbs that genuinely re-attempt or validate.
RECOVERY_COMMAND_TOKENS = (
    "validate-workflow-guardrails",
    "validate-workspace-artifacts",
    "run-reliability-suite",
    "validate-project-harness",
    "profile_index.json",
)


@dataclass(frozen=True)
class WorkflowGuardResult:
    workspace: str
    ok: bool
    status: str
    current_json_path: str
    current_markdown_path: str
    evidence_path: str
    error_count: int
    warning_count: int

    def summary(self) -> dict[str, Any]:
        return {
            "artifact_type": "workflow_guard_harness_result",
            "version": HARNESS_VERSION,
            "generated_by": "validate-workflow-guardrails",
            **asdict(self),
        }


class WorkflowGuardHarness:
    def __init__(
        self,
        repo_root: str | Path,
        workspace: str | Path,
        *,
        command_log: str | Path | None = None,
        roster_severity: str = "warning",
    ) -> None:
        self.repo_root = Path(repo_root).resolve()
        self.workspace = (self.repo_root / workspace).resolve()
        self.workspace_rel = _rel(self.workspace, self.repo_root)
        self.layout = WorkspaceLayout(project_root=self.workspace)
        self.command_log = self._resolve_optional(command_log)
        self.roster_severity = roster_severity if roster_severity in {"error", "warning"} else "warning"

    def run(self) -> WorkflowGuardResult:
        self._validate_workspace()
        self.layout.ensure_runtime_dirs()
        findings = []
        findings.extend(self._check_artifacts())
        findings.extend(self._check_trajectory())
        findings.extend(self._check_command_log())
        findings.extend(self._check_roster_utilization())
        findings.extend(self._check_required_specialists_fired())
        findings.extend(self._check_stalled_steps())
        findings.extend(self._check_unsupported_commands())
        findings.extend(self._check_failed_without_retry())
        findings.extend(self._check_completion_after_unrecovered_failures())
        findings.extend(self._check_incomplete_workflow())
        findings.extend(self._check_session_monitored())
        findings.extend(self._check_repeated_commands())
        findings.extend(self._check_generated_sql_raw_paths())
        findings.extend(self._check_hand_edited_generated_artifacts())
        findings.extend(self._check_throwaway_reader_scripts())
        findings.extend(self._check_vision_review_done())
        findings.extend(self._check_dashboard_screener_clean())
        error_count = sum(1 for item in findings if item["severity"] == "error")
        warning_count = sum(1 for item in findings if item["severity"] == "warning")
        report = {
            "artifact_type": "workflow_guard_harness/current.json",
            "version": HARNESS_VERSION,
            "generated_by": "validate-workflow-guardrails",
            "workspace": self.workspace_rel,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "ok": error_count == 0,
            "status": "passed" if error_count == 0 else "failed",
            "summary": {
                "errors": error_count,
                "warnings": warning_count,
                "findings": len(findings),
            },
            "findings": findings,
            "next_commands": self._next_commands(findings),
        }

        report_dir = self.layout.reports_dir / "workflow_guard_harness"
        evidence_dir = self.layout.evidence_dir / "workflow_guard_harness"
        report_dir.mkdir(parents=True, exist_ok=True)
        evidence_dir.mkdir(parents=True, exist_ok=True)
        current_json = report_dir / "current.json"
        current_md = report_dir / "current.md"
        evidence_path = evidence_dir / "current.json"
        current_json.write_text(json.dumps(report, indent=2, default=str) + "\n", encoding="utf-8")
        evidence_path.write_text(json.dumps(report, indent=2, default=str) + "\n", encoding="utf-8")
        current_md.write_text(_render_markdown(report), encoding="utf-8")
        return WorkflowGuardResult(
            workspace=self.workspace_rel,
            ok=bool(report["ok"]),
            status=str(report["status"]),
            current_json_path=_rel(current_json, self.repo_root),
            current_markdown_path=_rel(current_md, self.repo_root),
            evidence_path=_rel(evidence_path, self.repo_root),
            error_count=error_count,
            warning_count=warning_count,
        )

    def _validate_workspace(self) -> None:
        if not self.workspace.exists():
            raise FileNotFoundError(f"workspace not found: {self.workspace_rel}")
        if self.workspace == self.repo_root or not self.workspace.is_relative_to(self.repo_root):
            raise ValueError(f"workspace must be inside repo root: {self.workspace}")

    def _resolve_optional(self, value: str | Path | None) -> Path | None:
        if value is None:
            return None
        path = Path(value)
        return (self.repo_root / path).resolve() if not path.is_absolute() else path.resolve()

    def _check_vision_review_done(self) -> list[dict[str, Any]]:
        """A screener run stages screenshots for the agent's vision review;
        a report still pending means nobody (agent or human) actually looked
        at the rendered dashboard — the visual gate silently didn't happen."""
        from core.dashboard.screener import vision_review_pending

        if not vision_review_pending(self.repo_root, self.workspace_rel):
            return []
        report_rel = (
            f"{self.workspace_rel}/interns/reports/dashboard_screener/current.json"
        )
        return [
            _finding(
                "error",
                "dashboard_vision_review_pending",
                "Dashboard screener ran but its staged screenshots/chart crops were "
                "never vision-reviewed; the dashboard cannot be marked done until "
                "every staged image is read and judged.",
                artifact=report_rel,
                recommendation=(
                    "Read EVERY image under interns/reports/dashboard_screener/shots/ "
                    "(each page, each sub-tab, each per-chart crop), then record the "
                    f"pass: uv run workspace-dashboard --workspace {self.workspace_rel} "
                    "--record-vision-review --reviewed-by <name> --notes <findings>"
                ),
            )
        ]

    def _check_dashboard_screener_clean(self) -> list[dict[str, Any]]:
        """A dashboard whose screener found DETERMINISTIC defects (empty chart,
        currency-on-count, summed averages, empty tab) must not be marked done.
        These are hard, machine-checkable findings -- distinct from the subjective
        vision review -- so they block regardless of whether a human looked."""
        findings: list[dict[str, Any]] = []
        for sub in ("dashboard_screener", "dashboard_export_screener"):
            path = self.layout.reports_dir / sub / "current.json"
            if not path.exists():
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if data.get("ok", True):
                continue
            defects: list[str] = []
            for page in data.get("pages") or data.get("artifacts") or []:
                for err in page.get("errors") or []:
                    defects.append(f"{page.get('page') or page.get('kind')}: {err}")
            defects.extend(data.get("measure_semantics_findings") or [])
            defects.extend(data.get("palette_findings") or [])
            message = (
                f"{sub} found deterministic defects: " + "; ".join(defects[:6])
                if defects else f"{sub} reported not-ok."
            )
            findings.append(_finding(
                "error",
                f"{sub}_defects",
                message,
                artifact=f"{self.workspace_rel}/interns/reports/{sub}/current.json",
                recommendation=(
                    "Fix the flagged charts/measures, regenerate the dashboard, and "
                    f"re-run: uv run workspace-dashboard --workspace {self.workspace_rel} "
                    "--screen"
                ),
            ))
        return findings

    def _check_generated_sql_raw_paths(self) -> list[dict[str, Any]]:
        """Flag a raw dataset reader (read_csv_auto/read_parquet of a literal
        path) in generated SQL OUTSIDE a `CATALOG BOOTSTRAP` block. Generated KPI
        / pipeline SQL must read through the catalog_raw_* views the bootstrap
        block defines; a raw path elsewhere bypasses governance + breaks the
        cwd-independent execution contract. Ref: core-audit ob-harness.md."""
        findings: list[dict[str, Any]] = []
        candidate_dirs = [
            self.layout.generated_dir / "solutions",
            self.layout.generated_dir / "pipeline",
        ]
        for directory in candidate_dirs:
            if not directory.exists():
                continue
            for sql_file in sorted(directory.glob("*.sql")):
                try:
                    text = sql_file.read_text(encoding="utf-8")
                except OSError:
                    continue
                in_bootstrap = False
                for line in text.splitlines():
                    upper = line.upper()
                    if "CATALOG BOOTSTRAP" in upper:
                        # "END CATALOG BOOTSTRAP" closes; any other CATALOG
                        # BOOTSTRAP marker opens the exempt region.
                        in_bootstrap = "END" not in upper
                        continue
                    if in_bootstrap:
                        continue
                    low = line.lower()
                    if "read_csv_auto(" in low or "read_parquet(" in low:
                        findings.append(
                            _finding(
                                "error",
                                "generated_sql_raw_path_outside_bootstrap",
                                f"Generated SQL `{sql_file.name}` reads a raw dataset path "
                                "outside the CATALOG BOOTSTRAP block; read through the "
                                "catalog_raw_* views instead.",
                                artifact=_rel(sql_file, self.repo_root),
                                recommendation="Regenerate the SQL so raw read_csv_auto/read_parquet "
                                "calls live only in the catalog bootstrap block.",
                            )
                        )
                        break  # one finding per file is enough
        return findings

    def _check_artifacts(self) -> list[dict[str, Any]]:
        findings = []
        registry = _load_json(self.layout.contracts_dir / "kpi_registry.json")
        mapping = _load_json(self.layout.contracts_dir / "kpi_feature_mapping.json")
        panel = _load_json(self.layout.reports_dir / "blocker_question_panel" / "current.json")
        profile_index = _load_json(self.layout.profiles_dir / "profile_index.json")
        profile_columns = _profile_columns(profile_index)

        for idx, kpi in enumerate(registry.get("kpis") or [], start=1):
            for feature in _split_features(str(kpi.get("cuts") or "")):
                if _is_generic_temporal_placeholder(feature) and _key(feature) not in profile_columns:
                    findings.append(
                        _finding(
                            "error",
                            "invented_temporal_feature",
                            f"Registry KPI #{idx} contains generic temporal feature `{feature}` with no matching allowed profile column.",
                            artifact=_rel(self.layout.contracts_dir / "kpi_registry.json", self.repo_root),
                            recommendation="Regenerate or repair KPI parsing so source terms such as Month(ServiceDate) stay source-backed.",
                        )
                    )

        for kpi in mapping.get("kpis") or []:
            source_text = " ".join(
                str(kpi.get(key) or "") for key in ("name", "description", "metric", "cuts")
            )
            for feature in kpi.get("features") or []:
                if not isinstance(feature, dict):
                    continue
                name = str(feature.get("feature") or "")
                if _is_generic_temporal_placeholder(name) and _key(name) not in profile_columns:
                    findings.append(
                        _finding(
                            "error",
                            "unproven_mapping_feature",
                            f"KPI `{kpi.get('kpi_id')}` has unresolved generic feature `{name}` that is not present in profile evidence.",
                            artifact=_rel(self.layout.contracts_dir / "kpi_feature_mapping.json", self.repo_root),
                            recommendation="Resolve the original source date term before asking a blocker question.",
                            details={"source_text": source_text},
                        )
                    )

        panel_feature = str(panel.get("feature") or "")
        if panel and _is_generic_temporal_placeholder(panel_feature) and _key(panel_feature) not in profile_columns:
            findings.append(
                _finding(
                    "error",
                    "blocker_panel_invented_feature",
                    f"Current blocker panel asks about `{panel_feature}`, but no matching profile column exists.",
                    artifact=_rel(
                        self.layout.reports_dir / "blocker_question_panel" / "current.json",
                        self.repo_root,
                    ),
                    recommendation="Regenerate blocker panel after fixing KPI parser/source-row normalization.",
                )
            )
        if panel and panel.get("status") == "needs_user_answer" and not panel.get("evidence_files"):
            findings.append(
                _finding(
                    "warning",
                    "blocker_panel_missing_evidence_files",
                    "Current blocker panel has no evidence files listed.",
                    artifact=_rel(
                        self.layout.reports_dir / "blocker_question_panel" / "current.json",
                        self.repo_root,
                    ),
                    recommendation="Include source KPI row and profile artifacts before asking the user.",
                )
            )
        return findings

    def _check_command_log(self) -> list[dict[str, Any]]:
        if not self.command_log:
            return []
        if not self.command_log.exists():
            return [
                _finding(
                    "error",
                    "missing_command_log",
                    f"Command log not found: {_rel(self.command_log, self.repo_root)}",
                    recommendation="Pass a JSONL command log produced by session-snapshot or compatible tooling.",
                )
            ]
        records = _load_jsonl(self.command_log)
        findings = []
        commands = [str(item.get("command") or "") for item in records if isinstance(item, dict)]
        for index, record in enumerate(records):
            if not isinstance(record, dict):
                continue
            command = str(record.get("command") or "")
            status = str(record.get("status") or "")
            exit_code = record.get("exit_code")
            if not command:
                continue
            tokens = _command_tokens(command)
            first = tokens[0].lower() if tokens else ""
            if first in WINDOWS_UNIX_COMMANDS:
                findings.append(
                    _finding(
                        "error",
                        "unsupported_shell_command",
                        f"Command uses non-portable shell utility `{tokens[0]}`.",
                        command=command,
                        recommendation="Use project tools, `rg`, or PowerShell-native bounded commands.",
                    )
                )
            if _reads_raw_dataset(command) and not _mentions_profile(command):
                findings.append(
                    _finding(
                        "error",
                        "raw_data_read_before_profile",
                        "Command reads a raw dataset directly without referencing profile evidence.",
                        command=command,
                        recommendation="Read profile_index.json and relevant profile JSON first; use bounded samples only with a reason.",
                    )
                )
            if _failed(status, exit_code) and not _has_retry_or_recovery(commands[index + 1 : index + 4]):
                findings.append(
                    _finding(
                        "warning",
                        "failed_command_without_recovery",
                        "Failed command was not followed by an obvious retry, safer alternative, or project tool.",
                        command=command,
                        recommendation="Retry with the proper project tool or a platform-appropriate bounded command.",
                    )
                )
            lowered = command.lower()
            if "move-item" in lowered and "workspaces/" in lowered.replace("\\", "/"):
                findings.append(
                    _finding(
                        "error",
                        "workspace_source_mutation_without_delete_plan",
                        "Workspace source file was moved or renamed without a delete/mutation plan.",
                        command=command,
                        recommendation="Show a deletion/mutation plan and require explicit confirmation.",
                    )
                )
            if "prepare-kpi-blocker-panel" in lowered:
                findings.append(
                    _finding(
                        "error",
                        "skip_data_quality_before_kpi_blocker",
                        "KPI blocker workflow ran before data-quality review.",
                        command=command,
                        recommendation="Run data quality before KPI blocker questions.",
                        details={
                            "violated_rule_id": "skip_data_quality_before_kpi_or_generation",
                            "replacement_command": f"uv run harness data-quality --workspace {self.workspace_rel}",
                        },
                    )
                )
            if "generate-pipeline-sql" in lowered:
                findings.append(
                    _finding(
                        "error",
                        "generate_code_before_contracts_and_harnesses",
                        "Pipeline SQL generation ran before contract/harness gates.",
                        command=command,
                        recommendation="Run source-to-target, pipeline plan, and layered harness first.",
                    )
                )

        # Per-command stage time budget.
        for record in records:
            if not isinstance(record, dict):
                continue
            elapsed = record.get("elapsed_seconds")
            if isinstance(elapsed, (int, float)) and elapsed > STAGE_TIME_BUDGET_SECONDS:
                findings.append(
                    _finding(
                        "warning",
                        "stage_time_budget_exceeded",
                        f"Command ran {int(elapsed)}s, above the {STAGE_TIME_BUDGET_SECONDS}s "
                        "per-stage time budget.",
                        command=str(record.get("command") or ""),
                        details={"elapsed_seconds": elapsed},
                        recommendation="Investigate the long-running stage; bound/split the work or record why it is expected.",
                    )
                )

        # A prepared panel whose output is never read afterward (silent dead-end).
        lowered_commands = [c.lower().replace("\\", "/") for c in commands]
        for idx, low in enumerate(lowered_commands):
            if "-panel" not in low or "prepare-" not in low:
                continue
            later = lowered_commands[idx + 1 :]
            if not any(("panel" in c and ("current.md" in c or "current.json" in c or "question_panel" in c)) for c in later):
                findings.append(
                    _finding(
                        "error",
                        "panel_output_not_read",
                        "A blocker/decision panel was prepared but its output was never read before continuing.",
                        command=commands[idx],
                        recommendation="Read the panel's current.md/current.json before answering or routing onward.",
                    )
                )

        # External-source-workspace governance.
        if self._is_external_source_workspace():
            registry_read_seen = False
            for idx, low in enumerate(lowered_commands):
                if ("skills.md" in low or "/.agents/" in low or low.endswith(".agents")) and (
                    "get-content" in low or low.startswith("cat ") or "type " in low
                ):
                    registry_read_seen = True
                # Manual promotion of the generated selection without finalize-selection.
                if ("cp " in low or "copy-item" in low or low.startswith("copy ")) and "source_selection.json" in low:
                    findings.append(
                        _finding(
                            "error",
                            "manual_source_selection_promotion",
                            "Source selection was promoted by a manual file copy instead of finalize-selection.",
                            command=commands[idx],
                            recommendation="Use `uv run source-catalog finalize-selection` so provenance/approval is recorded.",
                        )
                    )
                is_route = any(tok in low for tok in WORKFLOW_ROUTE_TOKENS)
                if is_route and not registry_read_seen:
                    findings.append(
                        _finding(
                            "error",
                            "tool_registry_not_read_before_workflow_route",
                            "A workflow route was chosen before reading the tool registry (.agents/**/SKILLS.md).",
                            command=commands[idx],
                            recommendation="Read the tool registry first so the correct route is chosen for the workspace.",
                        )
                    )
                if any(tok in low for tok in KPI_ROUTE_TOKENS):
                    findings.append(
                        _finding(
                            "error",
                            "wrong_kpi_route_for_external_source_workspace",
                            "A KPI generation/resolution route was run on an external-source workspace; "
                            "it must go through the source-catalog/source-family route first.",
                            command=commands[idx],
                            recommendation="Run build-source-family-contracts / source-catalog before KPI routes.",
                        )
                    )
        return findings

    def _is_external_source_workspace(self) -> bool:
        """True when the workspace's profiles point at dataset files OUTSIDE the
        workspace tree (an external source root) AND its source selection targets
        a dataset — the shape that needs the source-catalog route, not KPI routes."""
        profile_index = _load_json(self.layout.profiles_dir / "profile_index.json")
        external = False
        for profile in profile_index.get("profiles") or []:
            if not isinstance(profile, dict):
                continue
            raw = str(profile.get("path") or "")
            if not raw:
                continue
            p = Path(raw)
            try:
                under_ws = self.workspace in p.resolve().parents or p.resolve() == self.workspace
            except OSError:
                under_ws = False
            if p.is_absolute() and not under_ws:
                external = True
                break
        if not external:
            return False
        selection = _load_json(self.workspace / "docs" / "source_selection.json")
        return any(
            isinstance(s, dict) and str(s.get("target_kind") or "") == "dataset"
            for s in (selection.get("sources") or [])
        )

    def _check_trajectory(self) -> list[dict[str, Any]]:
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        records = load_trajectory(trajectory_path)
        findings = []
        commands = [str(item.get("command") or "") for item in records if isinstance(item, dict)]
        for index, record in enumerate(records):
            if not isinstance(record, dict):
                continue
            command = str(record.get("command") or "")
            status = str(record.get("status") or "")
            exit_code = record.get("exit_code")
            if command:
                tokens = _command_tokens(command)
                first = tokens[0].lower() if tokens else ""
                if first in WINDOWS_UNIX_COMMANDS:
                    findings.append(
                        _finding(
                            "error",
                            "trajectory_unsupported_shell_command",
                            f"Trajectory command uses non-portable shell utility `{tokens[0]}`.",
                            artifact=_rel(trajectory_path, self.repo_root),
                            command=command,
                            recommendation="Use project tools, `rg`, or PowerShell-native bounded commands.",
                        )
                    )
                if _reads_raw_dataset(command) and not _mentions_profile(command):
                    findings.append(
                        _finding(
                            "error",
                            "trajectory_raw_data_read_before_profile",
                            "Trajectory command reads a raw dataset directly without referencing profile evidence.",
                            artifact=_rel(trajectory_path, self.repo_root),
                            command=command,
                            recommendation="Read profile_index.json and relevant profile JSON first; use bounded samples only with a reason.",
                        )
                    )
            if _failed(status, exit_code) and not _trajectory_has_recovery(
                records[index + 1 : index + 5],
                commands[index + 1 : index + 5],
            ):
                findings.append(
                    _finding(
                        "warning",
                        "trajectory_failed_step_without_recovery",
                        "Trajectory contains a failed step without a nearby retry or recovery event.",
                        artifact=_rel(trajectory_path, self.repo_root),
                        command=command,
                        recommendation="Record a retry/recovery event or rerun with a platform-appropriate project tool.",
                        details={
                            "event_type": record.get("event_type"),
                            "summary": record.get("summary"),
                        },
                    )
                )
        return findings

    def _next_commands(self, findings: list[dict[str, Any]]) -> list[str]:
        commands = []
        if any(item["code"] in {"invented_temporal_feature", "blocker_panel_invented_feature"} for item in findings):
            commands.append(f"uv run prepare-kpi-blocker-panel --workspace {self.workspace_rel} --domain healthcare")
        commands.append(f"uv run harness workflow-guardrails --workspace {self.workspace_rel}")
        return commands

    def _check_roster_utilization(self) -> list[dict[str, Any]]:
        """Warn when a generation panel ships without routing any agent/skill — the
        runtime complement to the roster-coverage unit test. Keeps the available
        agents/skills from sitting idle in the actual workflow output."""
        findings: list[dict[str, Any]] = []
        for label, path in _roster_panels(self.layout):
            if not path.exists():
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            if not (data.get("suggested_skills") or data.get("required_specialists")):
                findings.append(
                    _finding(
                        self.roster_severity,
                        "roster_not_routed",
                        f"{label} panel routes no agent or skill; the available roster is idle here.",
                        artifact=_rel(path, self.repo_root),
                        recommendation=(
                            "Attach routing_for(<stage>) so the panel carries required_specialists "
                            "and suggested_skills for the orchestrator to activate."
                        ),
                    )
                )
        return findings

    def _check_required_specialists_fired(self) -> list[dict[str, Any]]:
        """Enforce that listed `required_specialists` actually FIRED -- not just
        got printed in a panel. The runtime counterpart to roster_not_routed:
        roster_not_routed warns when NO specialist is listed; this fires when a
        COMPLETED stage listed specialists but the monitored session shows none of
        them activated (no hand-off note, no recorded review, no trajectory step
        naming them). Closes the advisory!=enforced gap (the session throughline).

        Conservative by design: only fires on a TERMINAL/complete stage in a
        MONITORED session (trajectory present). Mid-flight panels are skipped.
        """
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []  # unmonitored session is handled by _check_session_monitored
        records = load_trajectory(trajectory_path)
        if not records:
            return []

        fired = self._fired_specialists(records)
        findings: list[dict[str, Any]] = []
        seen_panels: set[str] = set()
        panels = list(_roster_panels(self.layout)) + [
            (f"workflow:{data.get('stage')}", path)
            for path, data in _workflow_stage_panels(self.layout)
        ]
        for label, path in panels:
            path = Path(path)
            if not path.exists():
                continue
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            required = [str(s) for s in (data.get("required_specialists") or []) if str(s).strip()]
            if not required:
                continue
            stage = str(data.get("stage") or "")
            status = str(data.get("status") or "")
            # Only enforce on a stage that has actually completed.
            terminal = any(term in _key(stage) for term in TERMINAL_STAGE_KEYWORDS) or any(
                term in _key(status) for term in TERMINAL_STAGE_KEYWORDS
            )
            if not terminal:
                continue
            unfired = [name for name in required if not self._specialist_fired(name, fired, records)]
            if not unfired or len(unfired) < len(required):
                # at least one required specialist fired -> the roster was used
                continue
            key = _rel(path, self.repo_root)
            if key in seen_panels:
                continue
            seen_panels.add(key)
            findings.append(
                _finding(
                    self.roster_severity,
                    "required_specialist_not_fired",
                    f"{label} stage completed but none of its required_specialists "
                    f"({', '.join(required)}) fired in this monitored session — the roster "
                    "was advisory only.",
                    artifact=key,
                    recommendation=(
                        "Activate the routed specialist(s) (record a hand-off note or the "
                        "specialist's review/decision) before completing the stage, or remove "
                        "specialists that are not actually required for this stage."
                    ),
                    details={"required_specialists": required, "unfired": unfired},
                )
            )
        return findings

    def _fired_specialists(self, records: list[dict[str, Any]]) -> set[str]:
        """Collect normalized tokens of specialists that show evidence of firing:
        recorded hand-off notes, a recorded kpi-analyst review, and trajectory
        commands/summaries that name an agent."""
        fired: set[str] = set()
        # Hand-off notes (one per specialist hand-off).
        handoffs_dir = self.layout.state_dir / "handoffs"
        if handoffs_dir.exists():
            for note in handoffs_dir.glob("*.md"):
                fired.add(_key(note.stem))
        # Recorded kpi-analyst review in any workflow session.
        for _path, data in _workflow_stage_panels(self.layout):
            review = data.get("kpi_analyst_review") or (data.get("summary") or {}).get(
                "kpi_analyst_review"
            )
            if review:
                fired.add(_key("kpi-analyst"))
                fired.add(_key("kpi_analyst"))
            for name in data.get("activated_specialists") or []:
                fired.add(_key(name))
        # Trajectory commands/summaries naming an agent.
        for record in records:
            if not isinstance(record, dict):
                continue
            blob = _key(f"{record.get('command') or ''} {record.get('summary') or ''}")
            if blob:
                fired.add(blob)
        return fired

    def _specialist_fired(
        self, name: str, fired: set[str], records: list[dict[str, Any]]
    ) -> bool:
        token = _key(name)
        if not token:
            return True  # cannot judge an empty name -> do not flag
        for signal in fired:
            if token and token in signal:
                return True
        return False

    def _check_stalled_steps(self) -> list[dict[str, Any]]:
        """Catch CLI-agent tool calls that never produced a result (stalled) and
        steps whose recorded duration crossed the slow-step threshold. Both point
        at a hung or runaway tool invocation around the governed workflow."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        records = load_trajectory(trajectory_path)
        findings: list[dict[str, Any]] = []

        open_starts: dict[str, dict[str, Any]] = {}
        for record in records:
            if not isinstance(record, dict):
                continue
            event_type = str(record.get("event_type") or "").lower()
            tool_id = _tool_id(record)
            if event_type == "tool_start" and tool_id:
                open_starts[tool_id] = record
            elif event_type == "tool_result" and tool_id:
                open_starts.pop(tool_id, None)

            duration = _duration_ms(record)
            if duration is not None and duration > SLOW_STEP_THRESHOLD_MS:
                findings.append(
                    _finding(
                        "warning",
                        "slow_step",
                        f"Trajectory step ran for {int(duration)} ms, above the {SLOW_STEP_THRESHOLD_MS} ms slow-step threshold.",
                        artifact=_rel(trajectory_path, self.repo_root),
                        command=str(record.get("command") or ""),
                        recommendation="Investigate the long-running tool call; split or bound the work, or record why it is expected.",
                        details={
                            "event_type": record.get("event_type"),
                            "duration_ms": duration,
                            "summary": record.get("summary"),
                        },
                    )
                )

        for tool_id, record in open_starts.items():
            findings.append(
                _finding(
                    "warning",
                    "stalled_step",
                    f"Tool start `{tool_id}` has no matching tool_result; the step appears stalled.",
                    artifact=_rel(trajectory_path, self.repo_root),
                    command=str(record.get("command") or ""),
                    recommendation="Record a tool_result/recovery event for the call or rerun it through the proper project tool.",
                    details={
                        "tool_id": tool_id,
                        "summary": record.get("summary"),
                    },
                )
            )
        return findings

    def _check_session_monitored(self) -> list[dict[str, Any]]:
        """Flag a session that clearly DID work but recorded no trajectory, so the
        reliability checks (stalls, retries, tool calls) can't see it. Makes session
        monitoring effectively mandatory — silent, unmonitored runs are surfaced."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        has_trajectory = bool(load_trajectory(trajectory_path)) if trajectory_path.exists() else False
        if has_trajectory:
            return []
        # Evidence that a governed workflow actually ran in this workspace.
        activity: list[str] = []
        for label, path in (
            ("applied_ops", self.layout.state_dir / "applied_ops.jsonl"),
            ("events", self.layout.state_dir / "events.jsonl"),
        ):
            try:
                if path.exists() and path.stat().st_size > 0:
                    activity.append(label)
            except OSError:
                continue
        if self.layout.solutions_dir.exists() and any(self.layout.solutions_dir.glob("kpi_*")):
            activity.append("generated_solutions")
        if not activity:
            return []  # nothing ran -> nothing to monitor
        return [
            _finding(
                "warning",
                "session_not_monitored",
                "Workflow activity occurred (" + ", ".join(activity) + ") but no session trajectory "
                "was recorded; stalls, retries, and tool calls in this session are not monitored.",
                artifact=_rel(trajectory_path, self.repo_root),
                command=f"uv run record-workspace-trajectory --workspace {self.workspace_rel} --render-only",
                recommendation=(
                    "Record session steps with record-workspace-trajectory (workspace-flow / apply-* "
                    "do this automatically) so reliability checks can see this session."
                ),
            )
        ]

    def _check_unsupported_commands(self) -> list[dict[str, Any]]:
        """Flag recorded commands that invoke an executable which is neither a known
        project tool nor a generic shell/git command. Catches the CLI agent reaching
        for an unsupported or hallucinated tool."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        records = load_trajectory(trajectory_path)
        if not records:
            return []
        allowed_tools = _allowed_tool_names(self.repo_root)
        if not allowed_tools:
            return []  # no tool roster discoverable -> cannot judge; degrade safely
        findings: list[dict[str, Any]] = []
        for record in records:
            if not isinstance(record, dict):
                continue
            command = str(record.get("command") or "")
            if not command:
                continue
            name = _invoked_tool_name(command)
            if not name:
                continue
            if name in allowed_tools or name in GENERIC_COMMANDS:
                continue
            findings.append(
                _finding(
                    "warning",
                    "unsupported_command",
                    f"Command invokes `{name}`, which is not a known project tool or generic shell/git command.",
                    artifact=_rel(trajectory_path, self.repo_root),
                    command=command,
                    recommendation="Use a documented project tool from .agents/tools.json or a generic shell/git command.",
                )
            )
        return findings

    def _check_failed_without_retry(self) -> list[dict[str, Any]]:
        """Promote a clearly unrecovered failure to an error. ``_check_trajectory``
        already warns on failed-without-recovery; this raises the severity to a
        blocker when the same command/step is not retried and no recovery or
        validation event follows within a short window."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        records = load_trajectory(trajectory_path)
        if not records:
            return []
        commands = [str(item.get("command") or "") for item in records if isinstance(item, dict)]
        findings: list[dict[str, Any]] = []
        for index, record in enumerate(records):
            if not isinstance(record, dict):
                continue
            status = str(record.get("status") or "")
            exit_code = record.get("exit_code")
            if not _failed(status, exit_code):
                continue
            window = records[index + 1 : index + 5]
            window_commands = commands[index + 1 : index + 5]
            command = str(record.get("command") or "")
            retried = bool(command) and any(
                command.strip() and command.strip() == other.strip() for other in window_commands
            )
            if retried or _trajectory_has_recovery(window, window_commands):
                continue
            findings.append(
                _finding(
                    "error",
                    "failed_without_recovery",
                    "Trajectory step failed and was not retried, recovered, or validated within the following steps.",
                    artifact=_rel(trajectory_path, self.repo_root),
                    command=command,
                    recommendation="Retry the step, route to a recovery/validation tool, or record why the failure is terminal.",
                    details={
                        "event_type": record.get("event_type"),
                        "status": status,
                        "summary": record.get("summary"),
                    },
                )
            )
        return findings

    def _check_completion_after_unrecovered_failures(self) -> list[dict[str, Any]]:
        """Block a completion/results/proof claim that follows unrecovered mutation
        failures. This is the Issue #6 gap: a run of failed `apply` commands
        (ValueError: Feature not found) was immediately followed by an "all KPIs
        fully proven / complete" claim, and nothing blocked it -- the completion
        command, being a `uv run ...`, was even mistaken for a recovery of those
        failures.

        Walks the trajectory in order; tracks whether there is an outstanding
        mutation failure that has NOT since been retried/recovered/validated. When a
        completion claim arrives while such a failure is outstanding, raises an
        error. Generic: failures, mutations, recoveries, and completion claims are
        all derived from structural tokens, never from a domain or a tool brand.
        """
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        records = load_trajectory(trajectory_path)
        if not records:
            return []

        findings: list[dict[str, Any]] = []
        outstanding: list[dict[str, Any]] = []  # unrecovered mutation failures so far
        for record in records:
            if not isinstance(record, dict):
                continue
            command = str(record.get("command") or "")
            status = str(record.get("status") or "")
            event_type = str(record.get("event_type") or "")
            summary = str(record.get("summary") or "")
            exit_code = record.get("exit_code")

            failed = _failed(status, exit_code)
            if failed and command and _is_mutation_command(command):
                outstanding.append(record)
                continue

            # A successful re-attempt of an outstanding mutation, or an explicit
            # recovery/validation event, clears the outstanding failures.
            if outstanding and not failed:
                recovered = (
                    event_type.lower() in {"retry", "recovery", "validation"}
                    or bool(record.get("recovery_for"))
                    or (
                        bool(command)
                        and _is_mutation_command(command)
                        and not _is_completion_claim(command=command)
                    )
                    or (
                        bool(command)
                        and not _is_completion_claim(command=command)
                        and any(term in command.lower() for term in RECOVERY_COMMAND_TOKENS)
                    )
                )
                if recovered:
                    outstanding = []

            if outstanding and _is_completion_claim(
                command=command, event_type=event_type, status=status, summary=summary
            ):
                failed_commands = [
                    str(item.get("command") or "") for item in outstanding
                ]
                findings.append(
                    _finding(
                        "error",
                        "completion_claim_over_unrecovered_failures",
                        f"A completion/results claim was made while {len(outstanding)} "
                        "mutation command(s) had failed and were never retried, "
                        "recovered, or validated.",
                        artifact=_rel(trajectory_path, self.repo_root),
                        command=command or summary,
                        recommendation=(
                            "Resolve or retry the failed mutation(s), or record an "
                            "explicit recovery/validation, before claiming completion "
                            "or emitting results."
                        ),
                        details={
                            "event_type": event_type,
                            "unrecovered_failed_commands": failed_commands,
                            "completion_summary": summary,
                        },
                    )
                )
                outstanding = []  # one finding per completion claim is enough
        return findings

    def _check_incomplete_workflow(self) -> list[dict[str, Any]]:
        """Conservatively flag a workflow session whose latest stage is a non-terminal
        awaiting stage while the trajectory shows no later progress. Only clear cases
        are reported to avoid false positives on in-flight work."""
        findings: list[dict[str, Any]] = []
        panels = _workflow_stage_panels(self.layout)
        if not panels:
            return []

        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        records = load_trajectory(trajectory_path) if trajectory_path.exists() else []
        progressed = _has_progress_after_panels(records, panels)

        for path, data in panels:
            stage = str(data.get("stage") or "").strip()
            if not stage or not _is_awaiting_stage(stage, data):
                continue
            if progressed:
                continue
            findings.append(
                _finding(
                    "warning",
                    "workflow_incomplete",
                    f"Workflow session is parked at non-terminal stage `{stage}` with no further trajectory progress.",
                    artifact=_rel(path, self.repo_root),
                    recommendation="Advance the workflow with the stage's next tool, or close the session if it is intentionally paused.",
                    details={"stage": stage, "status": data.get("status")},
                )
            )
        return findings

    def _check_repeated_commands(self) -> list[dict[str, Any]]:
        """Flag a deterministic command re-run >= REPEATED_COMMAND_THRESHOLD times in
        one session (after normalizing away volatile bits like --quiet/--diff and
        timestamps/session-ids). Re-running the same command to re-read its output is
        token waste — the printed artifact path should be read instead. Reads both the
        explicit command log and the recorded trajectory, reusing the existing readers."""
        commands: list[str] = []
        if self.command_log and self.command_log.exists():
            commands.extend(
                str(item.get("command") or "")
                for item in _load_jsonl(self.command_log)
                if isinstance(item, dict)
            )
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if trajectory_path.exists():
            commands.extend(
                str(item.get("command") or "")
                for item in load_trajectory(trajectory_path)
                if isinstance(item, dict)
            )

        counts: dict[str, int] = {}
        representative: dict[str, str] = {}
        for command in commands:
            normalized = _normalize_command(command)
            if not normalized:
                continue
            counts[normalized] = counts.get(normalized, 0) + 1
            representative.setdefault(normalized, command.strip())

        findings: list[dict[str, Any]] = []
        for normalized, count in counts.items():
            if count < REPEATED_COMMAND_THRESHOLD:
                continue
            findings.append(
                _finding(
                    "warning",
                    "repeated_identical_command",
                    f"Command `{representative[normalized]}` ran {count} times in one session; "
                    "re-running a deterministic command to re-read its output is redundant.",
                    artifact=_rel(trajectory_path, self.repo_root),
                    command=representative[normalized],
                    recommendation=(
                        "Run the command once with --quiet and read the printed artifact path "
                        "instead of re-running it to view truncated output."
                    ),
                    details={"normalized_command": normalized, "count": count},
                )
            )
        return findings

    def _check_hand_edited_generated_artifacts(self) -> list[dict[str, Any]]:
        """Flag a write/edit to a path under interns/generated/ (especially
        /solutions/). Generated artifacts are overwritten on regeneration, so a
        hand-edit there is lost — the fix belongs in the generator. Reads the recorded
        trajectory with the existing reader."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        findings: list[dict[str, Any]] = []
        for record in load_trajectory(trajectory_path):
            if not isinstance(record, dict):
                continue
            if not _is_file_mutation(record):
                continue
            for path in _mutation_paths(record):
                directory = _generated_artifact_dir(path)
                if not directory:
                    continue
                # Hand-editing generated EXECUTABLE SQL (interns/generated/solutions/)
                # is the failure mode that produced a stale, mismatched result packet
                # (BUG-024 cascade): it diverges the SQL from the execution-harness
                # hash and from the result packet. Treat it as a blocker, not advice.
                # Other generated dirs (contracts/profiles) stay a warning.
                severity = "error" if "solutions/" in directory else "warning"
                findings.append(
                    _finding(
                        severity,
                        "generated_artifact_hand_edited",
                        f"Generated artifact `{path}` under `{directory}` was hand-edited; "
                        "edits there are overwritten when the engine regenerates it.",
                        artifact=_rel(trajectory_path, self.repo_root),
                        command=str(record.get("command") or ""),
                        recommendation=(
                            "Fix the generator that produces this artifact instead of editing "
                            "the generated file; hand-edits are lost on the next regeneration."
                        ),
                        details={
                            "event_type": record.get("event_type"),
                            "edited_path": path,
                            "generated_dir": directory,
                        },
                    )
                )
                break  # one finding per mutating event is enough
        return findings

    def _check_throwaway_reader_scripts(self) -> list[dict[str, Any]]:
        """Flag a one-off reader script (read_*.py) created at the repo root. These are
        written purely to view truncated CLI output and are pure token/noise waste; the
        --quiet flags plus a direct file read remove the need. Reads the recorded
        trajectory with the existing reader."""
        trajectory_path = self.layout.state_dir / "trajectory.jsonl"
        if not trajectory_path.exists():
            return []
        findings: list[dict[str, Any]] = []
        for record in load_trajectory(trajectory_path):
            if not isinstance(record, dict):
                continue
            if not _is_file_mutation(record):
                continue
            for path in _mutation_paths(record):
                script = _reader_script_at_repo_root(path)
                if not script:
                    continue
                findings.append(
                    _finding(
                        "warning",
                        "throwaway_reader_script",
                        f"Throwaway reader script `{script}` was created at the repo root to view "
                        "truncated output.",
                        artifact=_rel(trajectory_path, self.repo_root),
                        command=str(record.get("command") or ""),
                        recommendation=(
                            "Re-run the source command with --quiet and read the printed artifact "
                            "path directly instead of writing a one-off reader script."
                        ),
                        details={
                            "event_type": record.get("event_type"),
                            "script_path": path,
                        },
                    )
                )
                break  # one finding per mutating event is enough
        return findings


def _roster_panels(layout) -> list[tuple[str, Any]]:
    reports = layout.reports_dir
    return [
        ("KPI generation", reports / "kpi_generation" / "current.json"),
        ("data model generation", reports / "data_model_generation" / "current.json"),
        ("engine generation", reports / "engine_generation" / "current.json"),
    ]


def _finding(
    severity: str,
    code: str,
    message: str,
    *,
    artifact: str = "",
    command: str = "",
    recommendation: str = "",
    details: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "severity": severity,
        "code": code,
        "message": message,
        "artifact": artifact,
        "command": command,
        "recommendation": recommendation,
        "details": details or {},
    }


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            data = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(data, dict):
            rows.append(data)
    return rows


def _profile_columns(profile_index: dict[str, Any]) -> set[str]:
    columns = set()
    for profile in profile_index.get("profiles") or []:
        if not isinstance(profile, dict):
            continue
        for column in profile.get("columns") or []:
            if isinstance(column, dict):
                columns.add(_key(column.get("name")))
    return columns


def _split_features(value: str) -> list[str]:
    features = []
    for part in re.split(r"[,;]", value):
        cleaned = part.strip()
        if not cleaned:
            continue
        if "=" in cleaned:
            cleaned = cleaned.split("=", 1)[0].strip()
        if ">" in cleaned:
            cleaned = cleaned.split(">", 1)[0].strip()
        features.append(cleaned)
    return features


def _is_generic_temporal_placeholder(value: str) -> bool:
    return _key(value) in GENERIC_TEMPORAL_PLACEHOLDERS


def _key(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(value or "").strip().lower()).strip("_")


def _command_tokens(command: str) -> list[str]:
    try:
        return shlex.split(command, posix=False)
    except ValueError:
        return command.split()


def _normalize_command(command: str) -> str:
    """Normalize a command to a stable key for "same invocation" detection. Lowercases,
    drops volatile flags (--quiet/--verbose/--diff/--render-only), and strips volatile
    value tokens that look like timestamps or session-ids so two otherwise-identical
    deterministic runs collapse to the same key."""
    tokens = [token for token in _command_tokens(command) if token]
    if not tokens:
        return ""
    kept: list[str] = []
    skip_next = False
    for token in tokens:
        if skip_next:
            skip_next = False
            continue
        lowered = token.lower()
        if lowered in _VOLATILE_COMMAND_FLAGS:
            continue
        # Drop a --flag=value pair whose flag carries a volatile value.
        if any(lowered.startswith(flag + "=") for flag in ("--session-id", "--session", "--run-id", "--timestamp")):
            continue
        if lowered in ("--session-id", "--session", "--run-id", "--timestamp"):
            skip_next = True
            continue
        if _is_volatile_value(token):
            continue
        kept.append(lowered)
    return " ".join(kept)


_TIMESTAMP_RE = re.compile(r"\d{4}-\d{2}-\d{2}([t_ ]\d{2}[:.]\d{2})?", re.IGNORECASE)
_SESSION_ID_RE = re.compile(r"^(sess|session|run)[-_][a-z0-9]+$", re.IGNORECASE)


def _is_volatile_value(token: str) -> bool:
    """A bare token that is a timestamp or a session/run id, which varies per run."""
    return bool(_TIMESTAMP_RE.fullmatch(token) or _SESSION_ID_RE.match(token))


def _is_file_mutation(record: dict[str, Any]) -> bool:
    event_type = str(record.get("event_type") or "").lower()
    return any(term in event_type for term in FILE_MUTATION_EVENT_TYPES)


def _mutation_paths(record: dict[str, Any]) -> list[str]:
    """Candidate file paths touched by a write/edit event, normalized to forward
    slashes. Looks in artifact, command, and common metadata path keys."""
    candidates: list[str] = []
    for value in (record.get("artifact"), record.get("command")):
        if value:
            candidates.append(str(value))
    metadata = record.get("metadata")
    if isinstance(metadata, dict):
        for field in ("path", "file_path", "target", "file", "edited_path", "written_path"):
            value = metadata.get(field)
            if value:
                candidates.append(str(value))
    return [candidate.replace("\\", "/") for candidate in candidates if candidate]


def _generated_artifact_dir(path: str) -> str:
    """Return the matched generated-artifact directory fragment for a path, else ""."""
    lowered = path.lower()
    for directory in GENERATED_ARTIFACT_DIRS:
        if directory in lowered:
            return directory
    return ""


def _reader_script_at_repo_root(path: str) -> str:
    """Return the read_*.py filename if the path is a one-off reader script at the repo
    root (no intermediate directory beyond the repo), else ""."""
    normalized = path.replace("\\", "/").strip()
    if not normalized:
        return ""
    # Repo-root only: the path must be a bare filename with no directory component
    # (allow a leading "./"). A script nested under any directory is not a root-level
    # throwaway reader.
    bare = normalized[2:] if normalized.startswith("./") else normalized
    if "/" in bare:
        return ""
    match = _READER_SCRIPT_RE.search(bare)
    return match.group(1) if match else ""


def _reads_raw_dataset(command: str) -> bool:
    lowered = command.lower()
    tokens = [token.lower() for token in _command_tokens(command)]
    if not tokens or tokens[0] not in RAW_DATA_READ_COMMANDS:
        return False
    return any(suffix in lowered for suffix in DATA_SUFFIXES) and "/datasets/" in lowered.replace("\\", "/")


def _mentions_profile(command: str) -> bool:
    lowered = command.lower().replace("\\", "/")
    return "/generated/profiles/" in lowered or "profile_index.json" in lowered


def _failed(status: str, exit_code: Any) -> bool:
    if status.lower() in {"failed", "error"}:
        return True
    try:
        return int(exit_code) != 0
    except (TypeError, ValueError):
        return False


def _has_retry_or_recovery(commands: list[str]) -> bool:
    """True when a following command is a genuine recovery/validation step.

    A recovery is an explicit re-attempt or a validation/recovery routing -- not
    merely "any later uv-run command". A completion/results claim is itself a
    ``uv run ...`` invocation, so treating every ``uv run`` as recovery let a
    completion claim silence the unrecovered failures that preceded it (Issue #6).
    Read profiles also count (the agent inspected evidence to recover).
    """
    for command in commands:
        lowered = command.lower()
        if _is_completion_claim(command=command):
            # A completion/results claim is the opposite of a recovery.
            continue
        if any(term in lowered for term in RECOVERY_COMMAND_TOKENS):
            return True
        if "get-content" in lowered or "select-object" in lowered:
            return True
    return False


def _is_mutation_command(command: str) -> bool:
    """A command that changes workspace state (apply/answer/finalize/commit-style)."""
    name = _invoked_tool_name(command)
    lowered = command.lower()
    return any(token in name for token in MUTATION_COMMAND_TOKENS) or any(
        token in lowered for token in MUTATION_COMMAND_TOKENS
    )


def _is_completion_claim(
    *,
    command: str = "",
    event_type: str = "",
    status: str = "",
    summary: str = "",
) -> bool:
    """True when any surface of a step asserts work is done / results are proven.

    Structural and domain-agnostic: matches completion/results/proof tokens in the
    command, event type, status, or summary so the claim is detected whichever
    surface carries it.
    """
    blob = " ".join((command, event_type, status, summary)).lower()
    if not blob.strip():
        return False
    return any(token in blob for token in COMPLETION_CLAIM_TOKENS)


def _trajectory_has_recovery(next_records: list[dict[str, Any]], next_commands: list[str]) -> bool:
    for record in next_records:
        event_type = str(record.get("event_type") or "").lower()
        if event_type in {"retry", "recovery"}:
            return True
        if record.get("recovery_for"):
            return True
    return _has_retry_or_recovery(next_commands)


def _tool_id(record: dict[str, Any]) -> str:
    """Stable id used to pair a tool_start with its tool_result. Prefers an explicit
    id in metadata, then a tool name, so the pairing tolerates either convention."""
    metadata = record.get("metadata")
    if isinstance(metadata, dict):
        for field in ("tool_id", "id", "call_id", "tool_call_id", "tool_use_id", "tool", "tool_name", "name"):
            value = metadata.get(field)
            if value not in (None, ""):
                return str(value)
    for field in ("tool_id", "tool", "tool_name"):
        value = record.get(field)
        if value not in (None, ""):
            return str(value)
    return ""


def _duration_ms(record: dict[str, Any]) -> float | None:
    metadata = record.get("metadata")
    source = metadata if isinstance(metadata, dict) else record
    value = source.get("duration_ms")
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _allowed_tool_names(repo_root: Path) -> set[str]:
    """Known project tool names, sourced from .agents/tools.json when present, else
    from the pyproject [project.scripts] table. Both are optional; an empty set is a
    safe degrade (the generic-command allowlist still suppresses false positives)."""
    names = _tool_names_from_agents_json(repo_root / ".agents" / "tools.json")
    if names:
        return names
    names = _tool_names_from_pyproject(repo_root / "pyproject.toml")
    if names:
        return names
    # Fallback: the tool roster is a property of the installed package, not the
    # workspace — locate the real repo pyproject relative to this module so the
    # check still works under a workspace-relative or sandboxed repo_root.
    module_repo = Path(__file__).resolve().parents[3]
    return _tool_names_from_pyproject(module_repo / "pyproject.toml")


def _tool_names_from_agents_json(path: Path) -> set[str]:
    if not path.exists():
        return set()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    names: set[str] = set()
    if isinstance(data, dict):
        tools = data.get("tools")
        if isinstance(tools, dict):
            names.update(str(key) for key in tools)
        elif isinstance(tools, list):
            for item in tools:
                if isinstance(item, dict):
                    name = item.get("name") or item.get("id")
                    if name:
                        names.add(str(name))
                elif isinstance(item, str):
                    names.add(item)
    return {name.lower() for name in names if name}


def _tool_names_from_pyproject(path: Path) -> set[str]:
    if not path.exists():
        return set()
    names: set[str] = set()
    in_scripts = False
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("["):
            in_scripts = stripped == "[project.scripts]"
            continue
        if in_scripts and "=" in stripped and not stripped.startswith("#"):
            name = stripped.split("=", 1)[0].strip().strip('"')
            if name:
                names.add(name.lower())
    return names


def _invoked_tool_name(command: str) -> str:
    """Return the effective executable/tool name for a command. Handles `uv run
    <name>` by returning <name>; otherwise returns the first token. Returns "" when
    no meaningful name can be extracted."""
    tokens = [token for token in _command_tokens(command) if token]
    if not tokens:
        return ""
    first = tokens[0].lower()
    if first == "uv" and len(tokens) >= 3 and tokens[1].lower() == "run":
        candidate = tokens[2]
        if candidate.startswith("-"):
            return "uv"
        return candidate.lower()
    return first


def _workflow_stage_panels(layout) -> list[tuple[Path, dict[str, Any]]]:
    """Workflow session panels that carry a `stage` field, from workflow_sessions and
    the reports tree. Only panels with a stage are returned."""
    panels: list[tuple[Path, dict[str, Any]]] = []
    seen: set[Path] = set()
    candidates: list[Path] = []
    sessions_dir = layout.workflow_sessions_dir
    if sessions_dir.exists():
        candidates.extend(sorted(sessions_dir.glob("*/current.json")))
    reports_dir = layout.reports_dir
    if reports_dir.exists():
        candidates.extend(sorted(reports_dir.glob("**/current.json")))
    for path in candidates:
        resolved = path.resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(data, dict) and str(data.get("stage") or "").strip():
            panels.append((path, data))
    return panels


def _is_awaiting_stage(stage: str, data: dict[str, Any]) -> bool:
    key = _key(stage)
    status = _key(data.get("status"))
    if any(term in key for term in TERMINAL_STAGE_KEYWORDS):
        return False
    if any(term in status for term in TERMINAL_STAGE_KEYWORDS):
        return False
    return any(term.strip("_") in key for term in AWAITING_STAGE_KEYWORDS) or any(
        term.strip("_") in status for term in AWAITING_STAGE_KEYWORDS
    )


def _has_progress_after_panels(records: list[dict[str, Any]], panels: list[tuple[Path, dict[str, Any]]]) -> bool:
    """Conservative progress signal: treat the workflow as still moving if the
    trajectory's newest event is later than the newest panel timestamp. Without
    comparable timestamps we assume progress (no flag) to avoid false positives."""
    panel_times = [
        _parse_ts(data.get("generated_at") or data.get("updated_at") or data.get("timestamp"))
        for _, data in panels
    ]
    panel_times = [value for value in panel_times if value is not None]
    if not panel_times:
        return True
    latest_panel = max(panel_times)
    event_times = [
        _parse_ts(record.get("timestamp"))
        for record in records
        if isinstance(record, dict)
    ]
    event_times = [value for value in event_times if value is not None]
    if not event_times:
        return False
    return max(event_times) > latest_panel


def _parse_ts(value: Any) -> datetime | None:
    if not value:
        return None
    text = str(value).strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(text)
    except ValueError:
        return None


def _render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Workflow Guard Harness",
        "",
        f"- Workspace: `{report['workspace']}`",
        f"- Status: `{report['status']}`",
        f"- Errors: `{report['summary']['errors']}`",
        f"- Warnings: `{report['summary']['warnings']}`",
        "",
        "## Findings",
        "",
    ]
    findings = report.get("findings") or []
    if findings:
        lines.append(
            render_markdown_table(
                ["Severity", "Code", "Message", "Recommendation"],
                [
                    [
                        item["severity"],
                        item["code"],
                        item["message"],
                        item["recommendation"],
                    ]
                    for item in findings
                ],
            )
        )
    else:
        lines.append("_No workflow guardrail findings._")
    lines.extend(["", "## Next Commands", ""])
    lines.extend(f"- `{command}`" for command in report.get("next_commands") or [])
    lines.append("")
    return "\n".join(lines)


def _rel(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve())).replace("\\", "/")
    except ValueError:
        return str(path).replace("\\", "/")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate workflow guardrails around governed tools.")
    parser.add_argument("--workspace", required=True)
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--command-log")
    parser.add_argument(
        "--roster-severity",
        choices=("warning", "error"),
        default="warning",
        help="Severity for the roster_not_routed finding (default: warning).",
    )
    args = parser.parse_args(argv)
    result = WorkflowGuardHarness(
        args.repo_root,
        args.workspace,
        command_log=args.command_log,
        roster_severity=args.roster_severity,
    ).run()
    print(json.dumps(result.summary(), indent=2))
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
