"""Regression: completion must not be reported when core/ changed mid-run.

Origin (2026-07-26 audit): seven core/ files were edited between pipeline
dispatches to clear a blocker -- including replacing the fan-trap detector with
`return []` -- and the pipeline had no opinion about it. Artifacts produced
earlier in the run were generated by different code than what ended up on disk,
so the run's own output could not be trusted or reproduced.
"""
from __future__ import annotations

import inspect
import unittest
from pathlib import Path

from core.onboarding.workspace import flow


class CoreTreeFingerprintTests(unittest.TestCase):
    def test_fingerprint_is_a_stable_hex_digest(self):
        first = flow._core_tree_fingerprint()
        second = flow._core_tree_fingerprint()
        self.assertEqual(first, second, "fingerprint must be stable for an unchanged tree")
        self.assertEqual(len(first), 64)
        int(first, 16)  # raises if not hex

    def test_fingerprint_changes_when_a_core_file_changes(self):
        from core.paths import PROJECT_ROOT

        probe = PROJECT_ROOT / "core" / "_tmp_drift_probe.py"
        before = flow._core_tree_fingerprint()
        probe.write_text("# drift probe\n", encoding="utf-8")
        try:
            after = flow._core_tree_fingerprint()
            self.assertNotEqual(before, after, "a new core/ file must change the fingerprint")
        finally:
            probe.unlink(missing_ok=True)
        self.assertEqual(flow._core_tree_fingerprint(), before, "removal must restore it")

    def test_pycache_is_ignored(self):
        # __pycache__ churns on every import; including it would make the guard
        # fire constantly and get switched off.
        src = inspect.getsource(flow._core_tree_fingerprint)
        self.assertIn("__pycache__", src)


class PipelineDriftGuardTests(unittest.TestCase):
    def setUp(self):
        self.src = inspect.getsource(flow.pipeline_main)

    def test_pipeline_captures_the_fingerprint_at_start(self):
        self.assertIn("core_fingerprint_at_start = _core_tree_fingerprint()", self.src)

    def test_pipeline_compares_before_emitting_completion(self):
        self.assertIn("core_drift", self.src)
        guard = self.src.find("core_fingerprint_at_start)")
        complete = self.src.find('result.status == "complete"')
        self.assertGreater(complete, -1)
        compare = self.src.find("!= core_fingerprint_at_start")
        self.assertGreater(compare, complete,
                           "the drift comparison must sit inside the completion branch")

    def test_drift_returns_nonzero(self):
        idx = self.src.find("core_drift")
        tail = self.src[idx:idx + 800]
        self.assertIn("return 2", tail)


if __name__ == "__main__":
    unittest.main()
